# Parcial 3

**IMPORTANTE**
- El código que incorpores *debe* poder ejecutarse en *este* Notebook en Visual Studio Code, en caso contrario el ejercicio ***será inválido***. Por favor,  verificá que el código se ejecute sin errores (aún en el caso en que la solución no sea del todo correcta).
- Al clicar "Ejecutar celda" en las celdas donde están los test deberían devolverse los resultados correctos.
- En estos ejercicios **no está permitido** importar ninguna biblioteca.
- **No está permitido** consultar internet. Cualquier consulta, por ejemplo el nombre de una instrucción que se hayan olvidado, debe ser hecha a los profesores.
- **No está permitido** utilizar el celular bajo ningún aspecto. Al alumno que utilce el celular le será retirado el examen.

**IMPORTANTE 2**
- Es conveniente escribír las pre y post condiciones.
- Seguí las convenciones respecto de nombres de variables, funciones y constantes.
- Evitar la utilización de funciones sofisticadas de Python. Toda función o método no visto en el curso no está permitido.

El parcial se aprueba con el 50% resuelto correctamente y eso equivale a una nota de 4.

**Ejercicio 1 (20%):  recursión sobre listas.**

1. Escribir  la función recursiva `suma_multiplos()` que recibe como parámetros una lista de enteros positivos  y un número entero positivo `m` y  devuelve la suma de los elementos de la lista que son múltiplos de `m`.
2. Escribir  la función recursiva `min_max()` que dada una lista no vacía  devuelve una $2$-úpla con el menor elemento de la lista y el mayor elemento de la lista.

Los ejercicios deben ser resueltos con funciones recursivas, de lo contrario  no suman puntos.

In [1]:
# definición de la funcion suma_multiplos
def suma_multiplos(integers_list: list, m: int):
    assert type(integers_list) == list, "Error"
    assert type(m) == int and m >= 0, "Error"

    if len(integers_list) == 0:
        return 0
    if integers_list[0] % m == 0:
        return integers_list[0] + suma_multiplos(integers_list[1:], m)
    return suma_multiplos(integers_list[1:], m)

In [2]:
# Test de la función suma_multiplos
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
m = 3
print(suma_multiplos(lista, m)) # 18
m = 2
print(suma_multiplos(lista, m)) # 30
m = 5
print(suma_multiplos(lista, m)) # 15
lista = [i  for i in range(100) if i%3 == 0]
m = 3
print(suma_multiplos(lista, m)) # 1683
m = 2
print(suma_multiplos(lista, m)) # 816
m = 5
print(suma_multiplos(lista, m)) # 315

18
30
15
1683
816
315


In [3]:
def min_max(integers_list):
    pass

In [4]:
# Test de la función min_max
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(min_max(lista)) # (1, 10)
lista = [i  for i in range(100) if i%3 == 0]
print(min_max(lista)) # (0, 99)
lista = [-19, -5, -18, 13, -11, 20, 1, 7, -16, 8]
print(min_max(lista)) # (-19, 20)
lista = [-89, 1, 24, -83, -76, 38, 78, 49, -61, 26, 22, -43, -15, 75, -18]
print(min_max(lista)) # (-89, 78)

None
None
None
None


**Ejercicio 2 (10%).**

La clase definida parcialmente en la siguiente celda de código, la clase `Nat`,  representa los números naturales. La única operación permitida en esta clase es la suma.

1. Implementar la suma en `Nat`.
2. Implementar la igualdad en `Nat`.
3. Hacer que el `print` de `Nat(n)` muestre en pantalla `Natural: n`.
4. Incorporar `assert` para garantizar que se trabajan con  enteros no negativos.


*Ayuda.*
- `__add__`:  es el método que permite sobreescrbir  `+` (la suma de dos elementos),
- `__eq__`:  es el método que permite sobreescrbir  `==`,
- `__str__`: es el método que permite sobresscribir la conversión a cadenas.




In [5]:
class Nat:
    def __init__(self, n):
        assert n > 0, "Error: n es menor o igual a cero"
        self.__num = n

    # definir suma
    def __add__(self, integer):
        assert isinstance(integer, Nat), "Error"
        assert type(integer.__num) == int and integer.__num > 0, "Error"
        return Nat(self.__num + integer.__num)

    # definir igualdad
    def __eq__(self, integer: int):
        assert isinstance(integer, Nat), "Error"
        assert type(integer.__num) == int and integer.__num > 0, "Error"
        return self.__num == integer.__num

    # definir conversión a cadenas
    def __str__(self):
        return f"Natural: {self.__num}"

In [6]:
# Tests
n = Nat(5)
print(n) # Natural: 5
m = Nat(3)
suma = n + m
print(suma) # Natural: 8
k = Nat(5)
print(n == k) # True
print(m == k) # False

Natural: 5
Natural: 8
True
False


**Ejercicio 3 (25%): clases.**


Desarrollar la clase `Evaluacion` para representar los alumnos de una clase y sus respectivas evaluaciones de  una materia. Cada alumno está determinado por su DNI y  como dato adicional se agrega su  nombre y apellido.

La clase `Evaluacion` debe tener los siguientes atributos y métodos:

Atributos:

* `dni`: el DNI del alumno evaluado.
* `nombre`: nombre y apellido del alumno.
* `materia`: la materia en que se lo evalúa al alumno.
* `notas`: un lista de enteros que representa las notas.

Los atributos deben ser privados.

Métodos getter:

* `dni()` :  devuelve el DNI  del alumno.
* `nombre()`: devuelve el nombre y apellido del alumno.
* `materia()`: devuelve el nombre de la materia.
* `regular()`:  devuelve `True` si regularizó la materia, `False` en caso contrario. Más abajo se explica el criterio de regularización.
* `promocionado()`:  devuelve `True` si promocionó la materia, `False` en caso contrario. Más abajo se explica el criterio de promoción.
* `promedio()`:  devuelve el promedio de todas las notas (sin redondear)

Además el `print()` debe mostrar por pantalla la información de la evaluación: nombre y apellido del alumno, DNI  del alumno, materia, notas obtenidas, si es regular o no,  si promocionó o no. En caso de haber promocionado la nota obtenida redondeada.

Métodos setter:

* `establecer_dni()`: se ingresa el número de DNI.
* `establecer_nombre()`: se establece el nombre y apellido del alumno.
* `establecer_materia()`: se establece la materia.     
* `agregar_nota(nota)`: recibe un entero `nota` del 0 al 10 y  agrega ese entero a las notas.

**Criterios para regularizar y promocionar**.

* Para regularizar el alumno debe haber aprobado al menos $2/3$  de los exámenes rendidos. Un  examen se aprueba con $4$.
* Para promocionar el alumno debe haber obtenido nota $6$ o superior en todos los exámenes y  debe tener promedio $\ge 7$. La nota que obtiene en ese caso es el promedio redondeado ($7.1$ redondea a $7$, $7.5$ redondea a $8$).    



In [7]:
class Evaluacion:
    def __init__(
        self,
        nombre: str = "",
        dni: str = "",
        materia: str = ""
    ):
        self.establecer_dni(dni)
        self.establecer_nombre(nombre)
        self.establecer_materia(materia)
        self.__notas = list()

    def dni(self) -> str:
        return self.__dni

    def nombre(self) -> str:
        return self.__nombre

    def materia(self) -> str:
        return self.__materia

    def establecer_dni(self, dni: str) -> None:
        assert type(dni) == str, "Error: dni debe ser un string"
        self.__dni = dni

    def establecer_nombre(self, nombre: str) -> None:
        assert type(nombre) == str, "Error: nombre debe ser string"
        self.__nombre = nombre.strip()

    def establecer_materia(self, materia: str) -> None:
        assert type(materia) == str, "Error: materia debe ser string"
        self.__materia = materia.strip()

    def agregar_nota(self, nota: int) -> None:
        assert type(nota) == int, "Error: nota no es un entero ente [0, 10]"
        self.__notas.append(nota)

    def promedio(self) -> float:
        if len(self.__notas) == 0:
            return 0

        return self.__sum_notas() / len(self.__notas)

    def regular(self) -> bool:
        if len(self.__notas) == 0:
            return False
        counter = 0
        for nota in self.__notas:
            if nota >= 4:
                counter += 1
        if counter > (2 * len(self.__notas) / 3):
            return True
        return False

    def promocionado(self) -> bool:
        for nota in self.__notas:
            if nota < 6:
                return False
        if self.promedio() >= 7:
            return True
        return False

    def __str__(self) -> str:
        to_return = f"{self.nombre()} ({self.dni()})\nMateria: {self.materia()}\nNotas: "
        for nota in self.__notas:
            to_return += f"{nota} "
        to_return += f"\nRegular: {self.regular()}\nPromocionado: {self.promocionado()}"
        if self.promocionado():
            to_return +=  f" con {round(self.promedio())}"

        return to_return + "\n"

    def __sum_notas(self, n: int = 0):
        suma = 0
        for nota in self.__notas:
            if nota >= n:
                suma += nota
        return suma

In [8]:
# Tests
alumno1 = Evaluacion('Juan Pérez', '12345678', 'Álgebra I')
alumno2 = Evaluacion('Ana López', '23456789', 'Álgebra I')
alumno3 = Evaluacion()
alumno3.establecer_nombre('Carlos Gómez')
alumno3.establecer_dni('34567890')
alumno3.establecer_materia('Álgebra II')
alumno4 = Evaluacion('María Rodríguez', '45678901', 'Álgebra II')

In [9]:
print(alumno1)
print(alumno2)
print(alumno3)
"""
Imprime:
Juan Pérez (12345678)
Materia: Álgebra I
Notas:
Regular: False
Promocionado: False

Ana López (23456789)
Materia: Álgebra I
Notas:
Regular: False
Promocionado: False

Carlos Gómez (34567890)
Materia: Álgebra II
Notas:
Regular: False
Promocionado: False
"""

Juan Pérez (12345678)
Materia: Álgebra I
Notas: 
Regular: False
Promocionado: False

Ana López (23456789)
Materia: Álgebra I
Notas: 
Regular: False
Promocionado: False

Carlos Gómez (34567890)
Materia: Álgebra II
Notas: 
Regular: False
Promocionado: False



'\nImprime:\nJuan Pérez (12345678)\nMateria: Álgebra I\nNotas:\nRegular: False\nPromocionado: False\n\nAna López (23456789)\nMateria: Álgebra I\nNotas:\nRegular: False\nPromocionado: False\n\nCarlos Gómez (34567890)\nMateria: Álgebra II\nNotas:\nRegular: False\nPromocionado: False\n'

In [10]:
alumno1.agregar_nota(2)
alumno1.agregar_nota(4)
alumno1.agregar_nota(6)
alumno1.agregar_nota(8)
alumno1.agregar_nota(2)
print(alumno1)
alumno2.agregar_nota(2)
alumno2.agregar_nota(4)
alumno2.agregar_nota(4)
alumno2.agregar_nota(8)
print(alumno2)
alumno3.agregar_nota(6)
alumno3.agregar_nota(7)
alumno3.agregar_nota(8)
alumno3.agregar_nota(8)
print(alumno3)
alumno4.agregar_nota(7)
alumno4.agregar_nota(5)
alumno4.agregar_nota(8)
alumno4.agregar_nota(9)
print(alumno4)
"""
Imprime:
Juan Pérez (12345678)
Materia: Álgebra I
Notas: 2 4 6 8 2
Regular: False
Promocionado: False

Ana López (23456789)
Materia: Álgebra I
Notas: 2 4 4 8
Regular: True
Promocionado: False

Carlos Gómez (34567890)
Materia: Álgebra II
Notas: 6 7 8 8
Regular: True
Promocionado: True con 7

María Rodríguez (45678901)
Materia: Álgebra II
Notas: 7 5 8 9
Regular: True
Promocionado: False
"""

Juan Pérez (12345678)
Materia: Álgebra I
Notas: 2 4 6 8 2 
Regular: False
Promocionado: False

Ana López (23456789)
Materia: Álgebra I
Notas: 2 4 4 8 
Regular: True
Promocionado: False

Carlos Gómez (34567890)
Materia: Álgebra II
Notas: 6 7 8 8 
Regular: True
Promocionado: True con 7

María Rodríguez (45678901)
Materia: Álgebra II
Notas: 7 5 8 9 
Regular: True
Promocionado: False



'\nImprime:\nJuan Pérez (12345678)\nMateria: Álgebra I\nNotas: 2 4 6 8 2\nRegular: False\nPromocionado: False\n\nAna López (23456789)\nMateria: Álgebra I\nNotas: 2 4 4 8\nRegular: True\nPromocionado: False\n\nCarlos Gómez (34567890)\nMateria: Álgebra II\nNotas: 6 7 8 8\nRegular: True\nPromocionado: True con 7\n\nMaría Rodríguez (45678901)\nMateria: Álgebra II\nNotas: 7 5 8 9\nRegular: True\nPromocionado: False\n'

**Ejercicio 4 (25%): entrada y salida.**

1. Crear un archivo `ejemplo.txt`.
2. Escribir en `ejemplo.txt`  las siguientes tres líneas


```
    Línea 1.
    La segunda línea.
    Otra línea.
    La cuarta línea
```

3. A  continuación abrir el archivo en modo lectura e imprimir las líneas pares (la primera línea es la línea 1).





In [11]:
try:
    with open("ejemplo.txt", "w") as f:
        f.write("Línea 1.\nLa segunda línea.\nOtra línea.\nLa cuarta línea")

    with open("ejemplo.txt", "r") as f:
        i = 1
        line = f.readline()
        while line:
            if i % 2 == 0:
                print(line)
            line = f.readline()
            i += 1
except Exception as err:
    print(f"Algo salio mal. {err}")

La segunda línea.

La cuarta línea


**Ejercicio 5 (20%): NumPy.**


1. Crear un  arreglo en NumPy a partir de la lista `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] ` e imprimirlo.
2. Usar una máscara booleana para identificar los elementos múltiplos de $3$  de una lista y mostrarlos. Probarlo para las listas



In [12]:
import numpy as np

array = np.arange(1, 11, 1)
print(array)

def array_mult_3(lista):
    array = np.array(lista)
    return array[array % 3 == 0]

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# Tests. Probar la solución de 2. para las siguientes listas
lista1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # imprime [3 6 9]
lista2 = [7, 1, 3, 4, 1, 8, 4, 3, 5, 4] # imprime [3 3]
lista3 = [9, 6, 9, 6, 7, 7, 7, 4, 3, 2, 3, 9, 6, 1, 7] # imprime [9 6 9 6 3 3 9 6]

print(array_mult_3(lista1))
print(array_mult_3(lista2))
print(array_mult_3(lista3))

[3 6 9]
[3 3]
[9 6 9 6 3 3 9 6]
